# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 09:01
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('georef', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeometriaToponimVersio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometria', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('idversio', models.ForeignKey(blank=True, db_column='idversio', null=True, on_delete=django.db.models.deletion.CASCADE, to='georef.Toponimversio')),
            ],
        ),
    ]
