# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-20 13:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('georef', '__first__'),
        ('georef_addenda', '0002_auto_20180214_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toponim_permission', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='georef.Toponim')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
