# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-20 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georef_addenda', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='permission_administrative',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='permission_filter_edition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='permission_visualize',
            field=models.BooleanField(default=False),
        ),
    ]
