# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-21 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georef_addenda', '0004_auto_20180220_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='permission_recurs_edition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='permission_toponim_edition',
            field=models.BooleanField(default=False),
        ),
    ]
