# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-22 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('georef_addenda', '0006_auto_20180221_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='permission_visualize',
            new_name='permission_tesaure_edition',
        ),
    ]
