# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-13 08:21
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('georef', '__first__'),
        ('georef_addenda', '0007_auto_20180222_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeometriaRecurs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometria', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('idrecurs', models.ForeignKey(blank=True, db_column='idrecurs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geometries', to='georef.Recursgeoref')),
            ],
        ),
    ]
