# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-15 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import georef.models


class Migration(migrations.Migration):

    dependencies = [
        ('georef_addenda', '0009_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='id',
            field=models.CharField(default=georef.models.pkgen, max_length=200, primary_key=True, serialize=False),
        ),
    ]
