# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-04 15:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('georef_addenda', '0011_helpfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='helpfile',
            old_name='file',
            new_name='h_file',
        ),
    ]
