# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-05 07:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('georef_addenda', '0012_auto_20180604_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpfile',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
