# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-10-17 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georef_addenda', '0013_helpfile_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(default='ca', max_length=10),
        ),
    ]
